name: Build
on:
  push:
jobs:
  run-tests:
    strategy:
      matrix:
        go-version:
          - 1.19.x
#          - 1.20.x

    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.3.1
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v3.1.0
      - name: Setup session
        uses: lhotari/action-upterm@v1  

#      - name: run tests
#        run: python index.py
#        #run: go test -vet all -race ./...

